//! Server host. Phase 7 ports surfaces by feature; no API redesign.

pub mod route;

pub use route::{
    compute_needs, route_decide, wire_surface_for, Api, NeedInput, ReqKind, RouteDecision, RouteEnv,
    WireSurface, LANE_CONTINUOUS, LANE_NONE, LANE_SERIAL, LANE_STATIC, NEED_BANK_FRONTIER,
    NEED_CONTINUATION_PUBLISH, NEED_CORRECTIVE_RECOVERY, NEED_DURABLE_RESPONSE, NEED_LIVE_FRONTIER,
    NEED_PER_ROW_SAMPLING, NEED_PREFILL_ONLY, NEED_STOP_SCAN, NEED_STREAMING, NEED_THINKING,
    NEED_TOKEN_IDS, NEED_TOOL_SCAN, REASON_COALESCE_OFF, REASON_CONT, REASON_CONT_BANK,
    REASON_CONT_UNAVAILABLE, REASON_NAMES, REASON_NEED_CONTINUATION_PUBLISH,
    REASON_NEED_CORRECTIVE_RECOVERY, REASON_NEED_DURABLE, REASON_NEED_LIVE_FRONTIER,
    REASON_NEED_PREFILL_ONLY, REASON_STATIC_NO_CONT, REASON_STATIC_PROMPT_BOUNDS, REASON_SURFACE,
    REASON_TOKEN_IDS_PROJECTION, REASON_TOOLS_COMPLETION,
};
